### PR TITLE
Update the extractor to use the ros_model_parser

### PR DESCRIPTION
**Pull request by ipa-nhg**
includes https://github.com/ipa320/ros-model-cloud/pull/39

Missed:
- Rossystem model support

### CODE REVIEW

**Comment by ipa-nhg** [comment]
Related to https://github.com/ipa320/ros_model_parser/pull/7

**Comment by ipa-nhg** [comment]
To test the changes please follow these instructions:

`git clone https://github.com/ipa-nhg/ros-model-cloud -b UseRosModelParser`

Melodic (copy-paste from docu https://github.com/ipa-nhg/ros-model-cloud/tree/UseRosModelParser/docker/melodic#use-the-docker-container-to-run-the-ros-model-plugin-for-haros):

```
cd ros-model-cloud/docker
docker build --tag=haros_melodic -f melodic/Dockerfile .
docker run -it haros_melodic:latest /haros_runner.sh hokuyo_node hokuyo_node node . /root/ws https://github.com/ros-drivers/hokuyo_node
```

Noetic (copy-paste from docu https://github.com/ipa-nhg/ros-model-cloud/tree/UseRosModelParser/docker/noetic#use-the-docker-container-to-run-the-ros-model-plugin-for-haros):

```
cd ros-model-cloud/docker
docker build --tag=haros_noetic -f noetic/Dockerfile .
docker run -it haros_noetic:latest /haros_runner.sh cob_sick_s300 cob_sick_s300 node . /root/ws https://github.com/ipa320/cob_driver
```

Foxy (copy-paste from docu https://github.com/ipa-nhg/ros-model-cloud/tree/UseRosModelParser/docker/foxy#use-the-docker-container-to-run-the-ros-model-plugin-for-haros):

```
cd ros-model-cloud/docker
docker build --tag=haros_foxy -f foxy/Dockerfile .
 docker run -it haros_foxy:latest /haros_runner.sh sick_scan2 sick_generic_caller node . /root/ws https://github.com/SICKAG/sick_scan2
```


The foxy test is not working, you will not get the model back, but it should compile and end without errors

**Comment by ipa-hsd** [comment]
Output for melodic :+1:
```
Print of the model: hokuyo_node.ros:
~~~~~~~~~~~
PackageSet {
  CatkinPackage hokuyo_node { 
    Artifact hokuyo_node {
      Node { name hokuyo_node
        Publishers {
          Publisher { name 'scan' message 'sensor_msgs.LaserScan'}}}}
}}
~~~~~~~~~~~
###########
```

**Comment by ipa-nhg** [comment]
This PR can be closed in favor of: https://github.com/ipa320/ros-model-extractors

**Pull request closed without merging**
